/*
 * HyperOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject21 struct {
	Name        string                 `json:"name"`
	Vm          string                 `json:"vm,omitempty"`
	Replica     string                 `json:"replica,omitempty"`
	Service     string                 `json:"service"`
	Description string                 `json:"description,omitempty"`
	Tag         map[string]interface{} `json:"tag,omitempty"`
}
