/*
 * HyperOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject60 struct {
	Name string `json:"name"`
	Service string `json:"service"`
	Credential VaultCredential `json:"credential,omitempty"`
	Retention float32 `json:"retention,omitempty"`
	Tag map[string]interface{} `json:"tag,omitempty"`
}
