/*
 * HyperOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type WebsiteCreate struct {
	Name string `json:"name"`
	Image string `json:"image"`
	Service string `json:"service"`
	Source WebsiteCreateSource `json:"source,omitempty"`
	Credential VaultCreateCredential `json:"credential,omitempty"`
	Tag map[string]interface{} `json:"tag,omitempty"`
}
