/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// InlineResponse400 struct for InlineResponse400
type InlineResponse400 struct {
	// error description
	Message string `json:"message,omitempty"`
}
