/*
HyperOne

HyperOne API

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ContainerProjectRegistryCredentialPatch struct for ContainerProjectRegistryCredentialPatch
type ContainerProjectRegistryCredentialPatch struct {
	Name string `json:"name"`
}

// NewContainerProjectRegistryCredentialPatch instantiates a new ContainerProjectRegistryCredentialPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerProjectRegistryCredentialPatch(name string) *ContainerProjectRegistryCredentialPatch {
	this := ContainerProjectRegistryCredentialPatch{}
	this.Name = name
	return &this
}

// NewContainerProjectRegistryCredentialPatchWithDefaults instantiates a new ContainerProjectRegistryCredentialPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerProjectRegistryCredentialPatchWithDefaults() *ContainerProjectRegistryCredentialPatch {
	this := ContainerProjectRegistryCredentialPatch{}
	return &this
}

// GetName returns the Name field value
func (o *ContainerProjectRegistryCredentialPatch) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContainerProjectRegistryCredentialPatch) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContainerProjectRegistryCredentialPatch) SetName(v string) {
	o.Name = v
}

func (o ContainerProjectRegistryCredentialPatch) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableContainerProjectRegistryCredentialPatch struct {
	value *ContainerProjectRegistryCredentialPatch
	isSet bool
}

func (v NullableContainerProjectRegistryCredentialPatch) Get() *ContainerProjectRegistryCredentialPatch {
	return v.value
}

func (v *NullableContainerProjectRegistryCredentialPatch) Set(val *ContainerProjectRegistryCredentialPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerProjectRegistryCredentialPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerProjectRegistryCredentialPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerProjectRegistryCredentialPatch(val *ContainerProjectRegistryCredentialPatch) *NullableContainerProjectRegistryCredentialPatch {
	return &NullableContainerProjectRegistryCredentialPatch{value: val, isSet: true}
}

func (v NullableContainerProjectRegistryCredentialPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerProjectRegistryCredentialPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


