/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// MetadataSource struct for MetadataSource
type MetadataSource struct {
	Filename string `json:"filename,omitempty"`
	Size float32 `json:"size,omitempty"`
}
