/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// InsightProjectJournalTransfer struct for InsightProjectJournalTransfer
type InsightProjectJournalTransfer struct {
	Project string `json:"project"`
}
