/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// IamProjectSaCredentialPatch struct for IamProjectSaCredentialPatch
type IamProjectSaCredentialPatch struct {
	Name string `json:"name"`
}
