/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// StorageProjectVaultResize struct for StorageProjectVaultResize
type StorageProjectVaultResize struct {
	Size float32 `json:"size"`
}
