/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// InvoiceDuplicate struct for InvoiceDuplicate
type InvoiceDuplicate struct {
	CreatedOn string `json:"createdOn,omitempty"`
	Id string `json:"id,omitempty"`
}
