/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
import (
	"time"
)
// AuthToken struct for AuthToken
type AuthToken struct {
	Id string `json:"id,omitempty"`
	Expiry time.Time `json:"expiry,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	CreatedOn time.Time `json:"createdOn,omitempty"`
	Access []AuthTokenAccess `json:"access,omitempty"`
	Name string `json:"name,omitempty"`
	ClientIp string `json:"clientIp,omitempty"`
	UserAgent string `json:"userAgent,omitempty"`
}
