/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package h1

import (
	"encoding/json"
)

// IamOrganisationPaymentAllocate struct for IamOrganisationPaymentAllocate
type IamOrganisationPaymentAllocate struct {
	Project string `json:"project"`
}

// NewIamOrganisationPaymentAllocate instantiates a new IamOrganisationPaymentAllocate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIamOrganisationPaymentAllocate(project string) *IamOrganisationPaymentAllocate {
	this := IamOrganisationPaymentAllocate{}
	this.Project = project
	return &this
}

// NewIamOrganisationPaymentAllocateWithDefaults instantiates a new IamOrganisationPaymentAllocate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIamOrganisationPaymentAllocateWithDefaults() *IamOrganisationPaymentAllocate {
	this := IamOrganisationPaymentAllocate{}
	return &this
}

// GetProject returns the Project field value
func (o *IamOrganisationPaymentAllocate) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *IamOrganisationPaymentAllocate) GetProjectOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *IamOrganisationPaymentAllocate) SetProject(v string) {
	o.Project = v
}

func (o IamOrganisationPaymentAllocate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["project"] = o.Project
	}
	return json.Marshal(toSerialize)
}

type NullableIamOrganisationPaymentAllocate struct {
	value *IamOrganisationPaymentAllocate
	isSet bool
}

func (v NullableIamOrganisationPaymentAllocate) Get() *IamOrganisationPaymentAllocate {
	return v.value
}

func (v *NullableIamOrganisationPaymentAllocate) Set(val *IamOrganisationPaymentAllocate) {
	v.value = val
	v.isSet = true
}

func (v NullableIamOrganisationPaymentAllocate) IsSet() bool {
	return v.isSet
}

func (v *NullableIamOrganisationPaymentAllocate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIamOrganisationPaymentAllocate(val *IamOrganisationPaymentAllocate) *NullableIamOrganisationPaymentAllocate {
	return &NullableIamOrganisationPaymentAllocate{value: val, isSet: true}
}

func (v NullableIamOrganisationPaymentAllocate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIamOrganisationPaymentAllocate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


