/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// Tag struct for Tag
type Tag struct {
	Id string `json:"id"`
	Key string `json:"key"`
	Value string `json:"value"`
}
