/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// DnsRecordset struct for DnsRecordset
type DnsRecordset struct {
	Id string `json:"id,omitempty"`
	// use '@' to reference the zone origin
	Name string `json:"name,omitempty"`
	Type string `json:"type"`
	Ttl float32 `json:"ttl,omitempty"`
	Record []DnsRecord `json:"record,omitempty"`
}
