/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// ProviderProjectAgentCredentialPatch struct for ProviderProjectAgentCredentialPatch
type ProviderProjectAgentCredentialPatch struct {
	Name string `json:"name"`
}
