/*
 * HyperOne
 *
 * HyperOne API
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package h1
// IpAssociated struct for IpAssociated
type IpAssociated struct {
	Ip string `json:"ip,omitempty"`
	Fip string `json:"fip,omitempty"`
	Netadp string `json:"netadp,omitempty"`
}
