/*
 * HyperOne API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ProjectLimit struct {
	Vm map[string]interface{} `json:"vm,omitempty"`
	Disk map[string]interface{} `json:"disk,omitempty"`
	Iso map[string]interface{} `json:"iso,omitempty"`
	Network map[string]interface{} `json:"network,omitempty"`
	Image map[string]interface{} `json:"image,omitempty"`
	Ip map[string]interface{} `json:"ip,omitempty"`
	Firewall map[string]interface{} `json:"firewall,omitempty"`
	Netgw map[string]interface{} `json:"netgw,omitempty"`
	Vault map[string]interface{} `json:"vault,omitempty"`
	Snapshot map[string]interface{} `json:"snapshot,omitempty"`
	Domain map[string]interface{} `json:"domain,omitempty"`
	LogArchive map[string]interface{} `json:"logArchive,omitempty"`
	Reservation map[string]interface{} `json:"reservation,omitempty"`
	Container map[string]interface{} `json:"container,omitempty"`
	Volume map[string]interface{} `json:"volume,omitempty"`
}
